version: "3.8"

services:
  pgdb:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - sample-api-pgdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sample-api-pgdb-data:
